# Generated by Django 2.2.2 on 2019-07-07 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haytunes', '0010_auto_20190509_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
