# Generated by Django 2.2.2 on 2019-07-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haytunes', '0012_auto_20190706_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
