# Generated by Django 2.2.2 on 2019-07-07 12:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('haytunes', '0013_auto_20190706_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must be Alphabetic', regex='^[a-zA-Z]*$')])),
                ('percentage', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
